List<String> stageNameList = [
  "Battlefield",
  "Small Battlefield",
  "Big Battlefield",
  "Final Destination",
  "New Donk City Hall",
  "Great Plateau Tower",
  "Moray Towers",
  "Dracula's Castle",
  "Mementos",
  "Yggdrasil's Altar",
  "Spiral Mountain",
  "King of Fighters Stadium",
  "Garreg Mach Monastery",
  "Spring Stadium",
  "Minecraft World",
  "Northern Cave",
  "Cloud Sea of Alrest",
  "Mishima Dojo",
  "Peach's Castle",
  "Kongo Jungle",
  "Hyrule Castle",
  "Super Happy Tree",
  "Dream Land",
  "Saffron City",
  "Mushroom Kingdom",
  "Princess Peach's Castle",
  "Rainbow Cruise",
  "Kongo Falls",
  "Jungle Japes",
  "Great Bay",
  "Temple",
  "Brinstar",
  "Yoshi's Story",
  "Fountain of Dreams",
  "Green Greens",
  "Corneria",
  "Venom",
  "Pokémon Stadium",
  "Onett",
  "Mushroom Kingdom II",
  "Brinstar Depths",
  "Big Blue",
  "Fourside",
  "Delfino Plaza",
  "Mushroomy Kingdom",
  "Figure-8 Circuit",
  "WarioWare, Inc.",
  "Bridge of Eldin",
  "Norfair",
  "Frigate Orpheon",
  "Yoshi's Island",
  "Halberd",
  "Lylat Cruise",
  "Pokémon Stadium 2",
  "Port Town Aero Dive",
  "Castle Siege",
  "Distant Planet",
  "Smashville",
  "New Pork City",
  "Summit",
  "Skyworld",
  "Shadow Moses Island",
  "Luigi's Mansion",
  "Pirate Ship",
  "Spear Pillar",
  "75m",
  "Mario Bros.",
  "Hanenbow",
  "Green Hill Zone",
  "Boxing Ring",
  "Gaur Plain",
  "Duck Hunt",
  "Wily Castle",
  "Super Mario Maker",
  "Suzaku Castle",
  "Midgar",
  "mbra Clock Tower",
  "3D Land",
  "Golden Plains",
  "Paper Mario",
  "Gerudo Valley",
  "Spirit Train",
  "Dream Land GB",
  "Unova Pokémon League",
  "Prism Tower",
  "Mute City SNES",
  "Magicant",
  "Arena Ferox",
  "Reset Bomb Forest",
  "Tortimer Island",
  "Balloon Fight",
  "Living Room",
  "Find Mii",
  "Tomodachi Life",
  "PictoChat 2",
  "Mushroom Kingdom U",
  "Mario Galaxy",
  "Mario Circuit",
  "Skyloft",
  "The Great Cave Offensive",
  "Kalos Pokémon League",
  "Coliseum",
  "Flat Zone X",
  "Palutena's Temple",
  "Gamer",
  "Garden of Hope",
  "Town and City",
  "Fit Studio",
  "Wrecking Crew",
  "Pilotwings",
  "Wuhu Island",
  "Windy Hill Zone",
  "Pac-Land",
].toList()
  ..sort();
